### ISSUE TITLE
MathJax not rendering at softcover.io

### ISSUE THREAD

**Issue by chkwon** [softcover/softcover#203] opened 2019-01-22 13:06 UTC
MathJax is not rendering at softcover.io.

See for example: http://manual.softcover.io/book/softcover_markdown

<img width="677" alt="screen shot 2019-01-22 at 8 04 52 am" src="https://user-images.githubusercontent.com/7596204/51537392-68f03100-1e1c-11e9-8e59-44f6d1b0d133.png">

Tested in Safari, Firefox, and Chrome, macOS.

**Comment by nickmerwin** [comment] 2019-01-22 18:02
This is fixed now, thank you for the heads up @chkwon!

**Closed by nickmerwin** 2019-01-22 18:02 UTC

**Comment by robconery** [comment] 2019-06-09 07:12
Can I ask what the problem was with this? I'm having the same issue with my local rendering but it seems to differ between machines. I can't trace what the issue is and it's driving me nuts!

**Comment by robconery** [comment] 2019-06-09 07:29
Never mind I figured it out. The `main.js` file (from softcover) wasn't loading as the server had crashed. The page loaded fine (I guess it's a SPA) but the server bits didn't. All fixed...
